### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by rtpguru101** [hootsuite/microservice-graph-explorer#19]
Hi
Sorry, technically this is not an issue - this is more of a question. In order to use the microservice graphy explorer, every http domain that i need to monitor the status on, should implement healthstatus-api ? Or can microservice graph explorer work in general for all http server monitors ?

**Comment by HootAdam** [comment]
Ideally all HTTP services implement the health checks api if you want to be able to traverse the graph and bubble up errors through the graph. If not, at the very least, the top entry point in your application needs to implement the health checks api. In side this service/application you would register all the other HTTP dependencies using a shallow status check that is not traversable. 

If you look at the default HTTP status checker, it assumes the HTTP service you are checking implements the health checks api. See https://github.com/hootsuite/healthchecks/blob/master/checks/httpsc/http.go and how it makes a request to the `/status/aggregate` endpoint.

I see two options for Status Checks for HTTP services that do not implement the health checks api:
1. If you want to check the HTTP service in real time, I would recommend implementing your own custom Status Check that probes the HTTP service on some endpoint that can be used to judge if the service is healthy or not. You can model this check off the HTTP check I shared above and use a different path and some other success/fail criteria. We have a section in the docs that shows how to implement your own Status Checks. See it here: https://github.com/hootsuite/healthchecks#writing-a-statuscheck
2. If you want to have a more passive check for your HTTP services, you can use the circuit breaker pattern where you wrap calls to your HTTP services in a circuit breaker and monitor the error responses and alert when the HTTP service returns more errors that a specific threshold. Circuit breakers can be useful for understanding if a specific endpoint is having issues on an HTTP service which could mean a partial outage or a breaking change on the HTTP service. This is particularly useful if you are calling external services. We already have a status check for this pattern at https://github.com/hootsuite/healthchecks/blob/master/checks/hystrixsc/hystrix.go Read more on Hystrix at https://github.com/afex/hystrix-go

Lastly, you can use both options 1 and 2 above in combination if you want to probe for real time health and also monitor the error rate from the HTTP service.

**Comment by rtpguru101** [comment]
Thank you so much for prompt reply. At present, I am not able to modify the HTTP servers that i need to modify to implement the healthcheck api. 
Lets keep the HTTP servers aside.

I used the instruction provided here: https://github.com/Bauer-Xcel-Media/node-healthchecks-api#installation

Can you give me an example of how to check Elastic Search and/or Mongo DB. Can you tell me what I am doing wrong ?
1. npm install --save healthchecks-api
2. npm install --save express
3. Created an app.js and added the following:

```
const healthCheck = require('healthchecks-api');
const express = require('express');


const startServer = async () => {
	const app = express();

await healthCheck(app,
       {
           adapter: 'express',
           service: {
               config: {
                  name: 'demo-app',
                  description: 'Nice demo application :)',
                  statsLinks: [ 'https://my-stats/demo-app' ],
                  logsLinks: [ 'https://my-logs/demo-app/info', 'https://my-logs/demo-app/debug' ],
                  checks: [
                      {
                          name: 'mongo',
                          url: 'mongodb://localhost:27017',
                          type: 'internal',
                          interval: 3000,
                          check: 'mongo',
                      }
                   ]
               },
           },
	   });
}

startServer();
```

4. Got the following error:
```
SyntaxError: Invalid regular expression: /^\status\(?:([^\/]+?))\/?$/: Unmatched ')'
    at new RegExp (<anonymous>)
    at pathtoRegexp (D:\nodework\healthstat\node_modules\path-to-regexp\index.js:128:10)
    at new Layer (D:\nodework\healthstat\node_modules\express\lib\router\layer.js:45:17)
    at Function.route (D:\nodework\healthstat\node_modules\express\lib\router\index.js:494:15)
    at Function.app.(anonymous function) [as get] (D:\nodework\healthstat\node_modules\express\lib\application.js:481:30)
    at module.exports (D:\nodework\healthstat\node_modules\healthchecks-api\lib\adapters\express.js:19:59)
    at Promise.all.map.route (D:\nodework\healthstat\node_modules\healthchecks-api\lib\health-check.js:132:63)
    at Array.map (<anonymous>)
    at module.exports (D:\nodework\healthstat\node_modules\healthchecks-api\lib\health-check.js:132:50)
```

**Comment by HootAdam** [comment]
Hi @rtpguru101,

This last issue seems specifically related the the node implementation of the health checks api. I think this specific question is better asked in that repo at https://github.com/Bauer-Xcel-Media/node-healthchecks-api
