### ISSUE TITLE
Self Signed Certificates

### ISSUE THREAD

**Issue by jahluwalia** [hootsuite/microservice-graph-explorer#6]
Is there a way to use microservice graph explorer with dependencies that have self signed certificates?

Thanks,
jas

**Comment by HootAdam** [comment]
Yes I think it should. MGE relies on status checks configured in your microservices via the Health Checks Framework. In general these checks will use the same connection that your services use for inter service communication so if your services can talk to each other, then the health checks and traversing should work

**Comment by jahluwalia** [comment]
Hi @HootAdam 

I'm not sure that's the case. Our microservices are written in node.js and can talk to each other because we are temporarily setting the following before making http requests: 
`process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`

 I noticed you guys were using play.ws. Supposedly i should be able to set the following in the explorer.conf file
```
play.ws.ssl.loose.allowWeakCiphers=true
play.ws.ssl.loose.acceptAnyCertificate=true
play.ws.ssl.loose.allowWeakProtocols=true
```

However, I think there is a bug in version 2.4 of the play framework that doesn't let those settings take hold. I believe MGE is using 2.4? Not sure. 

Here is a link that might discuss some of it
https://github.com/playframework/playframework/issues/5105

It looks like the play framework may have fixed this issue in later version (i think), any chance MGE will update their instance of the play framework? 

thanks,
jas

**Comment by HootAdam** [comment]
Ah so you are asking about the initial entry point into your service graph. I thought you were asking about communication by Health Checks framework after the request has entered into your graph. At this point we don't have a plan to upgrade to Play 2.5.

**Comment by HootAdam** [comment]
To confirm, we are currently on Play 2.4.2. See https://github.com/hootsuite/microservice-graph-explorer/blob/master/project/plugins.sbt#L4

**Comment by jahluwalia** [comment]
@HootAdam 

I see. Got any other suggestions or workarounds i could use? i'm out of ideas. 

Thanks,
Jas

**Comment by HootAdam** [comment]
From looking at that issue, you could try setting the config values directly on the ws client in https://github.com/hootsuite/microservice-graph-explorer/blob/master/app/actors/StatusPoller.scala
